### ISSUE TITLE
Can't see old questions.

### ISSUE THREAD

**Issue by hora** [pierreTklein/peer-tutoring-app#7]
What I did:

1. Asked my first question.
2. Tutor came over and answered my question. I clicked resolved.
3. A notification came up that suggested I ask another question if I'm still puzzled. I clicked the notification to dismiss it.
4. I have no current questions, and now I have 1 old question.
5. I clicked on the old questions accordion.

What happened:

- the accordion didn't expand
- clicking the + doesn't expand it either
- but, the caret toggles from expanded/closed; the +/- alternate.

Edit: showed up once I inspected the accordion for the old questions.

**Comment by pierreTklein** [comment]
Latest commit should have fixed this. Can you confirm? You might need to clear cache to receive new files.

**Comment by hora** [comment]
We can try this out when you're in the lab – need a tutor to replicate this.

Also: the email confirmation email ended up in my spam folder. Not sure whether there's something you can do to maybe avoid that?
